### ISSUE TITLE
GAK MAU RESPOND LUR BOTNYA

### ISSUE THREAD

**Issue by treymorkray** [thoriqazzikra/whatsapp-bot2#1]
ENTE COBA BOTV2 GABISA RESPOND LUR BOTNYA,Mohon DI fix Lur

**Comment by thoriqazzikra** [comment]
> ENTE COBA BOTV2 GABISA RESPOND LUR BOTNYA,Mohon DI fix Lur

Ga ngerespon dimananya ngab?

**Comment by thoriqazzikra** [comment]
Di ane ngerespon kok

**Comment by thoriqazzikra** [comment]
Ga ngerespon fiturnya atau semua fitur?

**Comment by SyauqiR** [comment]
woe thoriq eeks mampir donk ke github w JustPandaEver
