### ISSUE TITLE
ytmp3.play,ytmp4

### ISSUE THREAD

**Issue by SyauqiR** [thoriqazzikra/whatsapp-bot2#3]
masih eror ya ngap?

**Comment by SyauqiR** [comment]
dan ownerbotnya erorngap
![Uploading 2020-12-21.png…]()

**Comment by SyauqiR** [comment]
dan !gcinfo eror ngap

**Comment by SyauqiR** [comment]
![Uploading 2020-12-21 (2).png…]()

**Comment by m1dark** [comment]
Api dari Aruga Lagi Error Ngab, coba cari code api yang laen

**Comment by SyauqiR** [comment]
woe thoriq eeks mampir donk ke github w JustPandaEver
